export const BRAND_URLS: Record<string, string> = {
  'Bosch': 'https://www.bosch-aftermarket.com',
  'BOSCH': 'https://www.bosch-aftermarket.com',
  'Brembo': 'https://www.brembo.com',
  'brembo': 'https://www.brembo.com',
  'Castrol': 'https://www.castrol.com',
  'Continental': 'https://www.continental-engineparts.com',
  'Denso': 'https://www.denso-am.eu',
  'Febi Bilstein': 'https://www.febi.com',
  'FEBI': 'https://www.febi.com',
  'Filtron': 'https://www.filtron.eu',
  'FILTRON': 'https://www.filtron.eu',
  'GKN': 'https://www.gknautomotive.com',
  'Hella': 'https://www.hella.com',
  'HELLA': 'https://www.hella.com',
  'Lemförder': 'https://www.aftermarket.zf.com/go/en/lemfoerder',
  'LuK': 'https://www.aftermarket.schaeffler.com',
  'LUK': 'https://www.aftermarket.schaeffler.com',
  'Mahle': 'https://www.mahle-aftermarket.com',
  'MAHLE': 'https://www.mahle-aftermarket.com',
  'Mann-Filter': 'https://www.mann-filter.com',
  'MANN': 'https://www.mann-filter.com',
  'MANN FILTER': 'https://www.mann-filter.com',
  'Monroe': 'https://www.monroe.com',
  'NGK': 'https://www.ngkntk.com',
  'Sachs': 'https://www.aftermarket.zf.com/go/en/sachs',
  'SACHS': 'https://www.aftermarket.zf.com/go/en/sachs',
  'Schaeffler': 'https://www.aftermarket.schaeffler.com',
  'SKF': 'https://www.skf.com/group/products/vehicle-aftermarket',
  'Textar': 'https://textar.com',
  'TRW': 'https://www.aftermarket.zf.com/go/en/trw',
  'Valeo': 'https://www.valeoaftermarket.com',
  'VALEO': 'https://www.valeoaftermarket.com',
  'Victor Reinz': 'https://www.victorreinz.com',
  'ZF': 'https://www.aftermarket.zf.com',
  'Aisin': 'https://www.aisinaftermarket.eu',
  'Akebono': 'https://akebonobrakes.com',
  'Bilstein': 'https://www.bilstein.com',
  'Dayco': 'https://www.daycoaftermarket.com',
  'Delphi': 'https://www.delphiaftermarket.com',
  'Gates': 'https://www.gates.com',
  'GATES': 'https://www.gates.com',
  'KYB': 'https://kyb-europe.com',
  'Magneti Marelli': 'https://www.magnetimarelli-parts-and-services.com',
  'Meyle': 'https://www.meyle.com',
  'MEYLE': 'https://www.meyle.com',
  'Osram': 'https://www.osram.com/am',
  'Philips': 'https://www.philips.com/c-m-au/car-lights',
  'Shell': 'https://www.shell.com',
  'Liqui Moly': 'https://www.liqui-moly.com',
  'VDO': 'https://www.vdo-aftermarket.com'
};
